=head1 NAME

Mojolicious::Plugin::Alias - serve static files from aliased paths

=head1 SYNOPSIS

    $self->  # Mojolicious
    $self->plugin('alias', { '/images' => '/foo/bar/dir/images',
                             '/css' => '/here/docs/html/css' } );

    # Mojolicious::Lite
    plugin alias => { '/images' => '/ftp/pub/images' };

=head1 DESCRIPTION

L<Mojolicious::Plugin::Alias> extends the MojoX dispatcher for static files to
serve files from either a root directory or using a set of aliases that map URL
path parts to directories on the server.

When developing with the stand-alone webserver, this module allows you to
mimic server paths that might be used in your templates. 

=head1 CONFIGURATION

When installing the plugin, pass a reference to a hash of aliases (server
paths) and the directories to map to them. Installing the plugin
($plugin->register) will fail if these paths can't be found, or if the alias
doesn't start with a leading slash.

=head1 BUGS

It doesn't handle file not found errors properly :-(

=head1 AUTHOR

Dotan Dimet, C<dotan@corky.net>.

=head1 COPYRIGHT

Copyright (C) 2010, Dotan Dimet.

This program is free software, you can redistribute it and/or modify it under
the same terms as Perl 5.10.

=head1 SEE ALSO

L<Mojolicious>, L<Mojolicious::Guides>, L<http://mojolicious.org>.

=cut
